from __future__ import annotations

from .cli import *  # noqa: F403

COMMAND_OVERVIEW = """\
command groups (run `zwill <command> --help` for subcommands):

  getting started   init, status, guide, next
  survey data       survey, raw, question, respondent, answer, agent-material,
                    quarantine, commit, table, context
  inspection        report, prob-results
  model jobs        edsl build, workflow
  digital twins     twin-study, twin-experiment, twin-approach, twin-baseline,
                    twin-validate, twin-results, twin-benchmark
  agents            agent-list, agent-study
  misc              skills

New here? Run `zwill guide` for the end-to-end walkthrough, then `zwill next`
after each stage. Import file formats: `zwill guide show import-format`.
"""


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="zwill",
        description="Build survey datasets and validated digital-twin reports.",
        epilog=COMMAND_OVERVIEW,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    p = subparsers.add_parser("init")
    p.add_argument(
        "--output-dir",
        help="Directory that reports, bundles, and exports are contained under (relative paths rebase here). "
        "Persisted in .zwill/config.json. Defaults to zwill_work/; overridable per-run with the ZWILL_OUT env var.",
    )
    p.set_defaults(func=cmd_init)

    p = subparsers.add_parser("status")
    p.set_defaults(func=cmd_status)

    report = subparsers.add_parser("report").add_subparsers(dest="report_command", required=True)
    def add_report_build_args(parser: argparse.ArgumentParser) -> None:
        parser.add_argument("--survey", required=True)
        parser.add_argument("--path", help="Directory to write the report bundle. Defaults to <survey>_report/.")
        parser.add_argument("--job-id", action="append", help="Digital twin job id to include. Repeatable.")
        parser.add_argument("--jobs", help="Comma-separated digital twin job ids to include.")
        parser.add_argument("--model", help="Digital twin model or model label to include.")
        parser.add_argument("--audit-job-id", help="Twin job id to use for the run audit page. Defaults to the first selected twin job.")
        parser.add_argument("--example-limit", type=int, default=6, help="Maximum prompt examples to include in the audit page.")
        parser.add_argument("--probability-job-id", help="One-shot probability job id to include.")
        parser.add_argument("--probability-model", help="One-shot probability model or model label to include.")
        parser.add_argument(
            "--permutations",
            type=int,
            default=DEFAULT_REPORT_PERMUTATIONS,
            help=(
                "Permutation simulations for executive-summary chance tests. "
                f"Defaults to {DEFAULT_REPORT_PERMUTATIONS}; pass a larger value for slower, higher-resolution diagnostics."
            ),
        )
        parser.add_argument("--seed", type=int, default=20260701, help="Random seed for simulation diagnostics.")

    p = report.add_parser("list", help="List available reports for a survey and show readiness/suggested commands.")
    p.add_argument("--survey", required=True)
    p.add_argument("--format", choices=["table", "json"], default="table")
    p.add_argument("--path", help="Write JSON catalog output to this path.")
    p.set_defaults(func=cmd_report_list, table_output=True)
    p = report.add_parser("build", help="Build an incremental HTML report folder with an index page and all ready report pages.")
    add_report_build_args(p)
    p.set_defaults(func=cmd_report_build)
    p = report.add_parser("facts", help="Build deterministic fact artifacts for the report bundle.")
    add_report_build_args(p)
    p.set_defaults(func=cmd_report_facts)
    p = report.add_parser("analyze", help="Build deterministic analysis artifacts for the report bundle.")
    add_report_build_args(p)
    p.set_defaults(func=cmd_report_analyze)
    p = report.add_parser("render", help="Render report HTML from available deterministic facts and analysis.")
    add_report_build_args(p)
    p.set_defaults(func=cmd_report_render)
    project = subparsers.add_parser("project").add_subparsers(dest="project_command", required=True)
    p = project.add_parser("create", help="Create a project under .zwill/projects/.")
    p.add_argument("project_id")
    p.add_argument("--title")
    p.add_argument("--use", action="store_true", help="Set the new project as the active project.")
    p.set_defaults(func=cmd_project_create)
    p = project.add_parser("use", help="Set the active project.")
    p.add_argument("project_id")
    p.set_defaults(func=cmd_project_use)
    p = project.add_parser("current", help="Show the active project.")
    p.set_defaults(func=cmd_project_current)
    p = project.add_parser("list", help="List projects.")
    p.set_defaults(func=cmd_project_list)
    p = project.add_parser("show", help="Show project details.")
    p.add_argument("project_id", nargs="?")
    p.set_defaults(func=cmd_project_show)

    p = subparsers.add_parser("commit")
    p.add_argument("--survey", required=True)
    p.set_defaults(func=cmd_commit)

    p = subparsers.add_parser("table")
    p.add_argument("--survey", required=True)
    p.add_argument("--limit", type=int)
    p.set_defaults(func=cmd_table, table_output=True)

    edsl = subparsers.add_parser("edsl").add_subparsers(dest="edsl_command", required=True)
    p = edsl.add_parser("build", help="Build a durable EDSL .ep package for external execution with the ep CLI.")
    p.add_argument("--survey", required=True)
    p.add_argument("--path", required=True, help="Write the EDSL object to this .ep package path.")
    p.add_argument("--target", choices=["survey", "agent-list", "probability-job", "twin-probability-job", "rank-utility-twin-job", "numeric-twin-job", "open-codebook-job", "open-coding-job"], default="survey")
    p.add_argument("--question", action="append", help="Question name to include. Repeatable.")
    p.add_argument("--questions", help="Comma-separated question names to include.")
    p.add_argument("--exclude-question", action="append", help="Question name to exclude. Repeatable.")
    p.add_argument("--limit", type=int, help="Maximum number of agents to export.")
    p.add_argument(
        "--model",
        action="append",
        help="EDSL model for probability-job exports. Repeatable. Use service:model to set service per model.",
    )
    p.add_argument("--models", help="Comma-separated EDSL models for probability-job exports. Entries may be service:model.")
    p.add_argument("--service-name", help="EDSL service_name for unqualified probability-job models.")
    p.add_argument(
        "--model-param",
        action="append",
        help="Model parameter for probability-job exports. Use key=value for all models or service:model:key=value for one model. Repeatable.",
    )
    p.add_argument("--job-question-name", default="response_probabilities", help="Question name for probability-job exports.")
    p.add_argument("--n-themes", type=int, help="Maximum number of codebook themes for open-codebook-job exports.")
    p.add_argument("--sample-answers", type=int, help="Number of free-text answers to sample for open-codebook-job exports.")
    p.add_argument("--coded-question-name", help="Name for the coded multiple_choice question (open-coding-job; default <question>_coded).")
    p.add_argument("--heldout-question", action="append", help="Held-out question for twin-probability-job exports. Repeatable.")
    p.add_argument("--heldout-questions", help="Comma-separated held-out questions for twin-probability-job exports.")
    p.add_argument("--rank-task-id", action="append", help="Rank task id for rank-utility-twin-job exports. Repeatable.")
    p.add_argument("--rank-task-ids", help="Comma-separated rank task ids for rank-utility-twin-job exports.")
    p.add_argument("--approved-plan", help="Approved twin validation plan JSON required for twin-probability-job exports.")
    p.add_argument("--allow-unapproved", action="store_true", help="Explicitly allow an ad hoc twin export without an approved validation plan.")
    p.add_argument("--respondent", action="append", help="Respondent id to include in twin-probability-job exports. Repeatable.")
    p.add_argument("--respondents", help="Comma-separated respondent ids to include in twin-probability-job exports.")
    p.add_argument("--sample-respondents", type=int, help="Randomly sample this many respondents for twin-probability-job exports.")
    p.add_argument("--seed", type=int, help="Seed for --sample-respondents.")
    p.add_argument("--complete-cases", action="store_true", help="Only include respondents with answers for all selected context and held-out questions.")
    p.add_argument("--allow-missing-actual", action="store_true", help="Allow twin/rank exports whose validation targets are missing for some respondents.")
    p.add_argument("--balance-actual", action="store_true", help="Balance sampled respondents across actual held-out answer options.")
    p.add_argument("--stratify-actual", action="store_true", help="Sample respondents within actual held-out answer strata.")
    p.add_argument("--limit-respondents", type=int, help="Maximum number of respondents for twin-probability-job exports.")
    p.add_argument("--context-question", action="append", help="Question name to use as twin context. Repeatable.")
    p.add_argument("--context-questions", help="Comma-separated question names to use as twin context.")
    p.add_argument("--exclude-context-question", action="append", help="Question name to exclude from twin context. Repeatable.")
    p.add_argument("--leakage-exclusion", action="append", help="Target-specific context exclusion as heldout_question:<context_question | rank_task_id | glob*>. Repeatable.")
    p.add_argument("--context-question-count", type=int, help="Maximum number of context questions per respondent.")
    p.add_argument("--exclude-metadata-context", action="store_true", help="Do not include respondent metadata (panel covariates) in twin context. Included by default.")
    p.add_argument("--exclude-metadata-key", action="append", help="Respondent metadata key to exclude from twin context. Repeatable.")
    p.add_argument("--allow-empty-context", action="store_true", help="Allow twins with no observed answers (covariates only), e.g. when every candidate context question is held out. Off by default so holding out all questions at once is caught, not run silently.")
    p.add_argument("--include-survey-context", action="store_true", help="Include survey context markdown in exported EDSL Agent instructions.")
    p.add_argument("--include-agent-material", action="store_true", help="Include non-survey agent construction material in agent-list or twin job exports.")
    p.add_argument("--agent-material-kind", action="append", help="Only include agent material of this kind. Repeatable or comma-separated.")
    p.add_argument("--agent-material-tag", action="append", help="Only include agent material with this tag. Repeatable or comma-separated.")
    p.add_argument("--max-agent-material-chars", type=int, help="Maximum agent material characters per respondent.")
    p.add_argument("--twin-material", action="append", help="Supplemental twin material file. Repeatable. Supports Markdown, JSON, or JSONL.")
    p.add_argument("--max-twin-material-chars", type=int, help="Maximum supplemental twin material characters per scenario.")
    p.add_argument(
        "--prompt-variant",
        choices=["raw", "answer-commonness-confidence"],
        default="raw",
        help="Twin prompt variant for twin-probability-job exports.",
    )
    p.add_argument(
        "--twin-prompt-pipeline",
        help="JSON file describing an ordered twin prompt pipeline (reasoning/framing steps). "
        "The final step must include {{ output_contract }} and is the scored step; earlier steps "
        "pipe forward as {{ <step_name>.answer }}. Overrides --prompt-variant when set.",
    )
    p.add_argument("--traits-presentation-template", help="Jinja template for presenting AgentList traits in EDSL prompts.")
    p.add_argument("--traits-presentation-template-path", help="Path to a Jinja template for presenting AgentList traits in EDSL prompts.")
    p.add_argument("--no-default-traits-presentation-template", action="store_true", help="Use EDSL's default Agent trait presentation instead of zwill's survey-answer template.")
    p.add_argument("--quiet", action="store_true", help="Suppress stdout (the job is still written to --path). Useful when scripting.")
    p.set_defaults(func=cmd_edsl_build, raw_output=True)

    agent_list = subparsers.add_parser("agent-list").add_subparsers(dest="agent_list_command", required=True)
    p = agent_list.add_parser("inspect", help="Inspect an EDSL AgentList .ep package.")
    p.add_argument("--input-path", required=True, help="Path to an EDSL AgentList .ep package.")
    p.add_argument("--format", choices=["table", "json"], default="table")
    p.set_defaults(func=cmd_agent_list_inspect, table_output=True)

    agent_study = subparsers.add_parser("agent-study").add_subparsers(dest="agent_study_command", required=True)
    p = agent_study.add_parser("export", help="Build an EDSL Jobs .ep package that asks an AgentList a new question.")
    p.add_argument("--agent-list", required=True, help="Path to an EDSL AgentList .ep package.")
    p.add_argument("--path", required=True, help="Path to write the EDSL Jobs .ep package.")
    question_group = p.add_mutually_exclusive_group(required=True)
    question_group.add_argument("--question-path", help="Path to a JSON question spec or EDSL Question serialization.")
    question_group.add_argument("--question-name", help="Question name for an inline question spec.")
    p.add_argument("--question-type", help="Question type for an inline question spec.")
    p.add_argument("--question-text", help="Question text for an inline question spec.")
    p.add_argument("--question-option", action="append", help="Question option for inline multiple-choice specs. Repeatable.")
    p.add_argument("--model", action="append", help="EDSL model. Repeatable. Use service:model to set service per model.")
    p.add_argument("--models", help="Comma-separated EDSL models. Entries may be service:model.")
    p.add_argument("--service-name", help="EDSL service_name for unqualified models.")
    p.add_argument("--model-param", action="append", help="Model parameter. Use key=value or service:model:key=value. Repeatable.")
    p.add_argument("--quiet", action="store_true", help="Suppress stdout (the job is still written to --path). Useful when scripting.")
    p.set_defaults(func=cmd_agent_study_export, raw_output=True)
    p = agent_study.add_parser("import", help="Import serialized EDSL Results from an agent-study job.")
    p.add_argument("--input-path", required=True)
    p.add_argument("--job-id", help="Override the agent-study job id.")
    p.add_argument("--replace", action="store_true", help="Replace an existing imported result set with the same job id.")
    p.set_defaults(func=cmd_agent_study_import)
    p = agent_study.add_parser("report", help="Report imported agent-study answers.")
    p.add_argument("--job-id")
    p.add_argument("--model")
    p.add_argument("--format", choices=["table", "json", "csv", "html"], default="table")
    p.add_argument("--path", help="Write json/csv/html report output to this path.")
    p.set_defaults(func=cmd_agent_study_report, table_output=True)
    p = agent_study.add_parser("list", help="List imported agent-study runs.")
    p.add_argument("--format", choices=["table", "json"], default="table")
    p.set_defaults(func=cmd_agent_study_list, table_output=True)
    p = agent_study.add_parser("show", help="Show metadata for one imported agent-study run.")
    p.add_argument("--job-id", required=True)
    p.add_argument("--include-summary", action="store_true")
    p.set_defaults(func=cmd_agent_study_show)

    workflow = subparsers.add_parser("workflow").add_subparsers(dest="workflow_command", required=True)
    p = workflow.add_parser("run", help="Run a declarative workflow file and capture step artifacts.")
    p.add_argument("path", help="Path to a workflow .json/.yaml/.yml file.")
    p.add_argument("--var", action="append", help="Override workflow variable. Use key=value. Repeatable.")
    p.add_argument("--artifacts-dir", help="Directory for stdout/stderr files and manifest.json.")
    p.add_argument("--resume", action="store_true", help="Skip steps that already succeeded in the existing manifest.")
    p.set_defaults(func=cmd_workflow_run)
    p = workflow.add_parser("dry-run", help="Render a workflow file without executing commands.")
    p.add_argument("path", help="Path to a workflow .json/.yaml/.yml file.")
    p.add_argument("--var", action="append", help="Override workflow variable. Use key=value. Repeatable.")
    p.set_defaults(func=cmd_workflow_dry_run)
    p = workflow.add_parser("explain", help="Show rendered workflow steps without executing commands.")
    p.add_argument("path", help="Path to a workflow .json/.yaml/.yml file.")
    p.add_argument("--var", action="append", help="Override workflow variable. Use key=value. Repeatable.")
    p.set_defaults(func=cmd_workflow_explain)
    p = workflow.add_parser("pew-demo", help="Build the persistent PEW W154 DIFF1 demo project.")
    p.add_argument("--source-dir", help="Directory containing W154_DIFF1_metadata.json and W154_DIFF1_respondents.csv.")
    p.add_argument("--workdir", help="Persistent workdir to create or update.")
    p.add_argument("--fresh", action=argparse.BooleanOptionalAction, default=True, help="Clear prior .zwill state and imports first.")
    p.add_argument("--no-edsl", action="store_true", help="Skip EDSL survey and probability job export.")
    p.add_argument("--results-path", help="Serialized EDSL Results JSON or JSON.GZ to import after building the survey.")
    p.add_argument("--job-id", help="Override probability job id when importing --results-path.")
    p.add_argument("--question", action="append", help="Question name to include in the probability job. Repeatable.")
    p.add_argument("--questions", help="Comma-separated question names to include in the probability job.")
    p.add_argument("--exclude-question", action="append", help="Question name to exclude from the probability job. Repeatable.")
    p.add_argument("--model", action="append", default=["openai:gpt-5.5", "google:gemini-2.5-pro"], help="EDSL model for probability-job export. Repeatable.")
    p.add_argument("--models", help="Comma-separated EDSL models for probability-job export. Entries may be service:model.")
    p.add_argument("--service-name", help="EDSL service_name for unqualified probability-job models.")
    p.add_argument(
        "--model-param",
        action="append",
        default=[
            "google:gemini-2.5-pro:max_tokens=8192",
            "google:gemini-2.5-pro:thinking_budget=4096",
            "google:gemini-2.5-pro:temperature=0",
        ],
        help="Model parameter for probability-job export. Repeatable.",
    )
    p.add_argument("--job-question-name", default="response_probabilities")
    p.set_defaults(func=cmd_workflow_pew_demo)

    prob_results = subparsers.add_parser("prob-results").add_subparsers(dest="prob_results_command", required=True)
    p = prob_results.add_parser("import")
    p.add_argument("--survey", required=True)
    p.add_argument("--input-path", required=True)
    p.add_argument("--job-id")
    p.add_argument("--replace", action="store_true")
    p.set_defaults(func=cmd_probability_results_import)

    numeric_results = subparsers.add_parser("numeric-results").add_subparsers(dest="numeric_results_command", required=True)
    p = numeric_results.add_parser("import", help="Import and score continuous (quantile) twin predictions.")
    p.add_argument("--survey", required=True)
    p.add_argument("--input-path", required=True)
    p.add_argument("--job-id")
    p.add_argument("--replace", action="store_true")
    p.set_defaults(func=cmd_numeric_results_import)
    p = numeric_results.add_parser("report", help="Summarize numeric twin predictions (pinball/CRPS/coverage vs marginal baseline).")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id")
    p.add_argument("--format", choices=["json", "html"], default="json")
    p.add_argument("--path", help="Write the html report to this path.")
    p.set_defaults(func=cmd_numeric_results_report)

    open_coding = subparsers.add_parser("open-coding").add_subparsers(dest="open_coding_command", required=True)
    p = open_coding.add_parser("codebook-import", help="Store a derived codebook of themes for a free_text question.")
    p.add_argument("--survey", required=True)
    p.add_argument("--input-path", required=True, help="EDSL Results file from an open-codebook-job run.")
    p.add_argument("--question", help="Source free_text question (defaults to the one recorded in the results).")
    p.set_defaults(func=cmd_open_codebook_import)
    p = open_coding.add_parser("import", help="Create a coded multiple_choice question from an open-coding-job run.")
    p.add_argument("--survey", required=True)
    p.add_argument("--input-path", required=True, help="EDSL Results file from an open-coding-job run.")
    p.add_argument("--question", help="Source free_text question (defaults to the one recorded in the results).")
    p.add_argument("--coded-question-name", help="Name for the coded question (default <question>_coded).")
    p.add_argument("--replace", action="store_true", help="Overwrite an existing coded question and its answers.")
    p.set_defaults(func=cmd_open_coding_import)
    p = prob_results.add_parser("report")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id")
    p.add_argument("--model")
    p.add_argument("--format", choices=["table", "json", "html", "csv", "svg"], default="table")
    p.add_argument("--path", help="Write json/html/csv/svg report output to this path.")
    p.set_defaults(func=cmd_probability_results_report, table_output=True)
    twin_baseline = subparsers.add_parser(
        "twin-baseline",
        help="Cheap conditional baselines that score the same held-out questions as digital twins.",
    ).add_subparsers(dest="twin_baseline_command", required=True)
    p = twin_baseline.add_parser(
        "run",
        help="Fit an embedding + logistic conditional baseline and store its held-out predictions.",
    )
    p.add_argument("--survey", required=True)
    p.add_argument("--heldout-question", action="append", help="Held-out target question. Repeatable.")
    p.add_argument("--heldout-questions", help="Comma-separated held-out target questions.")
    p.add_argument("--sample-respondents", type=int, help="Optional random respondent sample size (debugging).")
    p.add_argument("--seed", type=int, help="Seed for --sample-respondents.")
    p.add_argument("--embedding-model", default="text-embedding-3-small", help="Embedding model name.")
    p.add_argument("--embedder", choices=["auto", "openai", "sentence-transformers", "hashing", "edsl"], default="auto", help="Embedding backend for the conditional baseline. 'auto' (default) tries the Expected Parrot endpoint first behind a short health probe (so an unavailable endpoint fails over in seconds instead of hanging), then a direct OpenAI key, then a local sentence-transformers model, then a built-in lexical embedder that always runs. 'sentence-transformers' forces the local model ([local-embeddings] extra); 'hashing' forces the zero-dependency lexical embedder; 'edsl' forces the remote Expected Parrot embeddings (no failover).")
    p.add_argument("--l2", type=float, default=1.0, help="L2 regularization strength for the logistic model.")
    p.add_argument("--job-id", help="Override the derived baseline job id.")
    p.add_argument("--replace", action="store_true", help="Overwrite existing predictions for this job id.")
    p.add_argument("--path", help="Also write the prediction rows as JSONL to this path.")
    p.set_defaults(func=cmd_twin_baseline_run)

    p = subparsers.add_parser(
        "twin-validate",
        help="Run the full twin validation flow (leakage audit + conditional baseline + bootstrap CIs + HTML report) for one or more twin jobs.",
    )
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", action="append", help="Imported twin job id to validate. Repeatable.")
    p.add_argument("--jobs", help="Comma-separated twin job ids to validate.")
    p.add_argument("--out", required=True, help="Output bundle directory for the report and diagnostics.")
    p.add_argument("--view", choices=["summary", "full"], default="full", help="HTML report view.")
    p.add_argument("--skip-baseline", action="store_true", help="Do not fit the conditional baseline.")
    p.add_argument("--require-baseline", action="store_true", help="Fail (rather than warn) if the baseline cannot run.")
    p.add_argument("--skip-leakage-audit", action="store_true", help="Do not run the context leakage audit.")
    p.add_argument("--skip-bootstrap", action="store_true", help="Do not compute bootstrap confidence intervals.")
    p.add_argument("--embedding-model", default="text-embedding-3-small", help="Embedding model for the baseline.")
    p.add_argument("--embedder", choices=["auto", "openai", "sentence-transformers", "hashing", "edsl"], default="auto", help="Embedding backend for the baseline. 'auto' (default) tries the Expected Parrot endpoint first behind a short health probe (so an unavailable endpoint fails over in seconds instead of hanging), then a direct OpenAI key, then a local sentence-transformers model, then a built-in lexical embedder that always runs. 'sentence-transformers' forces the local model ([local-embeddings] extra); 'hashing' forces the zero-dependency lexical embedder; 'edsl' forces the remote Expected Parrot embeddings (no failover).")
    p.add_argument("--l2", type=float, default=1.0, help="L2 regularization strength for the baseline logistic model.")
    p.add_argument("--leakage-threshold", type=float, default=0.7, help="Cramer's V threshold for flagging leakage.")
    p.add_argument("--min-pair-rows", type=int, default=30, help="Minimum co-answered respondents for a leakage pair.")
    p.add_argument("--n-boot", type=int, default=1000, help="Bootstrap resamples.")
    p.add_argument("--ci", type=float, default=0.95, help="Confidence level (0-1).")
    p.add_argument("--seed", type=int, default=0, help="Random seed for baseline and bootstrap.")
    p.add_argument("--env-path", help="Explicit .env file to load (for the baseline's embedding key). Defaults to the nearest .env above the current directory.")
    p.set_defaults(func=cmd_twin_validate)

    twin_results = subparsers.add_parser("twin-results").add_subparsers(dest="twin_results_command", required=True)
    p = twin_results.add_parser("import")
    p.add_argument("--survey", required=True)
    p.add_argument("--input-path", required=True)
    p.add_argument("--job-id")
    p.add_argument("--replace", action="store_true")
    p.add_argument("--merge", action="store_true", help="Upsert rows into an existing job (by respondent/held-out/model) instead of replacing it. Use to re-import recovered rows from twin-results retry-malformed without losing the rows that already scored.")
    p.add_argument("--allow-missing-actual", action="store_true", help="Import true holdout predictions whose scenarios omit actual_answer.")
    p.set_defaults(func=cmd_twin_results_import)
    p = twin_results.add_parser(
        "retry-malformed",
        help="Build a retry job containing only the scenarios whose model rows were dropped as malformed, so a couple of provider hiccups don't force a full re-run.",
    )
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", required=True, help="Imported twin job id whose malformed rows to retry.")
    p.add_argument("--job", required=True, help="The original exported EDSL job file that produced this job's results.")
    p.add_argument("--path", help="Where to write the retry Jobs.ep package. Defaults to the job directory's retry.ep.")
    p.set_defaults(func=cmd_twin_results_retry_malformed)
    p = twin_results.add_parser("export", help="Export stored digital twin predictions to CSV.")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", action="append", help="Job id to export. Repeatable.")
    p.add_argument("--jobs", help="Comma-separated job ids to export.")
    p.add_argument("--model", help="Model or model label to export.")
    p.add_argument("--question", action="append", help="Held-out question to export. Repeatable.")
    p.add_argument("--questions", help="Comma-separated held-out questions to export.")
    p.add_argument("--format", choices=["long", "wide"], default="long")
    p.add_argument("--path", help="Write CSV output to this path.")
    p.set_defaults(func=cmd_twin_results_export, table_output=True)
    p = twin_results.add_parser("package", help="Export stored digital twin predictions to CSV and zip it.")
    p.add_argument("--survey", required=True)
    p.add_argument("--manifest", help="Import/export manifest whose job ids should be packaged.")
    p.add_argument("--job-id", action="append", help="Job id to package. Repeatable.")
    p.add_argument("--jobs", help="Comma-separated job ids to package.")
    p.add_argument("--model", help="Model or model label to package.")
    p.add_argument("--question", action="append", help="Held-out question to package. Repeatable.")
    p.add_argument("--questions", help="Comma-separated held-out questions to package.")
    p.add_argument("--format", choices=["long", "wide"], default="long")
    p.add_argument("--path", required=True, help="Write CSV output to this path.")
    p.add_argument("--zip-path", help="Write zip output to this path. Defaults to --path with .zip suffix.")
    p.set_defaults(func=cmd_twin_results_package)
    p = twin_results.add_parser(
        "bootstrap",
        help="Bootstrap confidence intervals over respondents for model scores and paired deltas vs a baseline.",
    )
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", action="append", help="Digital twin job id. Repeatable.")
    p.add_argument("--jobs", help="Comma-separated digital twin job ids.")
    p.add_argument("--manifest", help="Twin results manifest whose job ids to include.")
    p.add_argument("--model", help="Restrict to a single model or model label.")
    p.add_argument("--question", action="append", help="Held-out question to include. Repeatable.")
    p.add_argument("--questions", help="Comma-separated held-out questions to include.")
    p.add_argument("--baseline-model", help="Model label to compute paired deltas against (e.g. baseline:conditional-embedding).")
    p.add_argument("--n-boot", type=int, default=1000, help="Number of bootstrap resamples.")
    p.add_argument("--seed", type=int, default=0, help="Bootstrap random seed.")
    p.add_argument("--ci", type=float, default=0.95, help="Confidence level (0-1).")
    p.add_argument("--path", help="Write the full bootstrap result JSON to this path.")
    p.add_argument("--svg-path", help="Write a paired-difference bootstrap forest plot SVG.")
    p.set_defaults(func=cmd_twin_results_bootstrap)
    p = twin_results.add_parser(
        "leakage-audit",
        help="Flag context questions that near-deterministically predict a target (Cramer's V on observed answers).",
    )
    p.add_argument("--survey", required=True)
    p.add_argument("--target", action="append", help="Target question to audit. Repeatable.")
    p.add_argument("--targets", help="Comma-separated target questions to audit.")
    p.add_argument("--job-id", action="append", help="Derive targets from this job's held-out questions. Repeatable.")
    p.add_argument("--jobs", help="Comma-separated job ids whose held-out questions become targets.")
    p.add_argument("--threshold", type=float, default=0.7, help="Cramer's V at or above which a pair is flagged.")
    p.add_argument("--min-pair-rows", type=int, default=30, help="Minimum co-answered respondents to score a pair.")
    p.add_argument("--path", help="Write the full audit JSON (all pairs) to this path.")
    p.set_defaults(func=cmd_twin_results_leakage_audit)
    p = twin_results.add_parser("report")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", action="append", help="Digital twin job id. Repeatable.")
    p.add_argument("--jobs", help="Comma-separated digital twin job ids.")
    p.add_argument("--model")
    p.add_argument("--format", choices=["table", "json", "csv", "html"], default="table")
    p.add_argument("--view", choices=["summary", "full"], default="full", help="HTML report view. `summary` writes a compact high-level diagnostics page; `full` includes row-level audit details.")
    p.add_argument("--path", help="Write json/html/csv report output to this path.")
    p.add_argument("--calibration-svg-path", help="Write the calibration reliability diagram as a standalone SVG.")
    p.set_defaults(func=cmd_twin_results_report, table_output=True)
    p = twin_results.add_parser("rank-report", help="Report rank-utility digital twin validation results.")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", help="Rank utility twin job id.")
    p.add_argument("--rank-task-id", action="append", help="Rank task id to include. Repeatable.")
    p.add_argument("--model", help="Model or model label to include.")
    p.add_argument("--format", choices=["table", "json", "csv", "html"], default="table")
    p.add_argument("--path", help="Write json/html/csv report output to this path.")
    p.set_defaults(func=cmd_rank_results_report, table_output=True)
    p = twin_results.add_parser("executive-summary", help="Build a deterministic twin validation summary with plots and diagnostics.")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", action="append", help="Digital twin job id. Repeatable.")
    p.add_argument("--jobs", help="Comma-separated digital twin job ids.")
    p.add_argument("--model", help="Model or model label to include.")
    p.add_argument("--question", action="append", help="Held-out question to include. Repeatable.")
    p.add_argument("--questions", help="Comma-separated held-out questions to include.")
    p.add_argument("--path", help="Write HTML report output to this path. Defaults to artifacts/<survey>_executive_summary.html.")
    p.add_argument("--markdown-path", help="Write Markdown companion output to this path. Defaults to --path with .md suffix.")
    p.add_argument("--permutations", type=int, default=20000, help="Permutation simulations for chance tests.")
    p.add_argument("--seed", type=int, default=20260701, help="Random seed for simulation diagnostics.")
    p.set_defaults(func=cmd_twin_results_executive_summary)
    p = twin_results.add_parser("compare-report", help="Compare two or more imported digital twin jobs side by side.")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", action="append", help="Digital twin job id. Repeatable.")
    p.add_argument("--jobs", help="Comma-separated digital twin job ids.")
    p.add_argument("--model", help="Restrict to one model or model label.")
    p.add_argument("--format", choices=["table", "json", "html"], default="html")
    p.add_argument("--path", help="Write json/html output to this path.")
    p.set_defaults(func=cmd_twin_results_compare_report, table_output=True)
    p = twin_results.add_parser("run-report", help="Audit a digital twin job's construction, import, and prompt examples.")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", required=True, help="Digital twin job id.")
    p.add_argument("--format", choices=["table", "json", "html"], default="html")
    p.add_argument("--path", help="Write json/html output to this path.")
    p.add_argument("--example-limit", type=int, default=6, help="Maximum prompt examples to include.")
    p.set_defaults(func=cmd_twin_results_run_report, table_output=True)
    p = twin_results.add_parser("calibrate-marginal", help="KL/IPF calibrate twin probabilities to target question marginals.")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", required=True, help="Source digital twin job id.")
    p.add_argument("--model", help="Source model or model label to calibrate.")
    p.add_argument("--question", action="append", help="Held-out question to calibrate. Repeatable.")
    p.add_argument("--questions", help="Comma-separated held-out questions to calibrate.")
    p.add_argument("--target", choices=["probability-job", "empirical"], default="probability-job")
    p.add_argument("--target-job-id", help="Target probability job id when --target probability-job.")
    p.add_argument("--target-probability-job-id", help=argparse.SUPPRESS)
    p.add_argument("--target-model", help="Target probability model or model label when the target job has multiple rows per question.")
    p.add_argument("--output-job-id", help="Job id for the derived calibrated twin rows.")
    p.add_argument("--max-iter", type=int, default=10000)
    p.add_argument("--tolerance", type=float, default=1e-12)
    p.add_argument("--replace", action="store_true")
    p.set_defaults(func=cmd_twin_results_calibrate_marginal)
    p = twin_results.add_parser("marginal-diagnostics", help="Compare twin-implied aggregate marginals to one-shot or empirical marginals.")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", action="append", help="Digital twin job id. Repeatable.")
    p.add_argument("--jobs", help="Comma-separated digital twin job ids.")
    p.add_argument("--model", help="Twin model or model label.")
    p.add_argument("--question", action="append", help="Held-out question to compare. Repeatable.")
    p.add_argument("--questions", help="Comma-separated held-out questions to compare.")
    p.add_argument("--target", choices=["probability-job", "empirical"], default="probability-job")
    p.add_argument("--target-job-id", help="Probability job id when --target probability-job.")
    p.add_argument("--target-model", help="Probability model or model label when the target job has multiple rows per question.")
    p.add_argument("--format", choices=["table", "json", "csv", "svg"], default="table")
    p.add_argument("--path", help="Write summary json/csv or chart SVG output to this path.")
    p.add_argument("--option-path", help="Write option-level CSV output when --format csv.")
    p.set_defaults(func=cmd_twin_results_marginal_diagnostics, table_output=True)

    twin_study = subparsers.add_parser("twin-study").add_subparsers(dest="twin_study_command", required=True)
    p = twin_study.add_parser("build", help="Build a digital-twin Jobs.ep package for external execution with the ep CLI.")
    p.add_argument("--survey", required=True)
    p.add_argument("--output-dir", default=".", help="Directory for default job/results/report paths.")
    p.add_argument("--job-path", help="Path to write the EDSL Jobs.ep package.")
    p.add_argument("--results-path", help="Expected Results.ep output path for the returned ep run command.")
    p.add_argument("--report-html", help="Path to write the HTML report. Defaults to output-dir/<survey>_twin_<job_id>_report.html.")
    p.add_argument("--report-json", help="Optional path to write the JSON report.")
    p.add_argument("--report-csv", help="Optional path to write the CSV report.")
    p.add_argument("--replace", action="store_true", help="Replace an existing imported result set with the same job id.")
    p.add_argument("--dry-run", action="store_true", help="Export the job and report planned paths without running model calls.")
    p.add_argument("--approved-plan", help="Approved twin validation plan JSON required before exporting or running a twin study.")
    p.add_argument("--allow-unapproved", action="store_true", help="Explicitly allow an ad hoc/debug twin study without an approved validation plan.")
    p.add_argument("--question", action="append", help=argparse.SUPPRESS)
    p.add_argument("--questions", help=argparse.SUPPRESS)
    p.add_argument("--exclude-question", action="append", help=argparse.SUPPRESS)
    p.add_argument("--heldout-question", action="append", help="Held-out question. Repeatable.")
    p.add_argument("--heldout-questions", help="Comma-separated held-out questions.")
    p.add_argument("--respondent", action="append", help="Respondent id to include. Repeatable.")
    p.add_argument("--respondents", help="Comma-separated respondent ids to include.")
    p.add_argument("--sample-respondents", type=int, help="Randomly sample this many respondents.")
    p.add_argument("--seed", type=int, help="Seed for --sample-respondents.")
    p.add_argument("--complete-cases", action="store_true", help="Only include respondents with all selected context and held-out answers.")
    p.add_argument("--balance-actual", action="store_true", help="Balance sampled respondents across actual held-out answer options.")
    p.add_argument("--stratify-actual", action="store_true", help="Sample respondents within actual-answer strata.")
    p.add_argument("--limit-respondents", type=int, help="Maximum number of respondents.")
    p.add_argument("--context-question", action="append", help="Question name to use as context. Repeatable.")
    p.add_argument("--context-questions", help="Comma-separated context question names.")
    p.add_argument("--exclude-context-question", action="append", help="Question name to exclude from context. Repeatable.")
    p.add_argument("--leakage-exclusion", action="append", help="Target-specific context exclusion as heldout_question:<context_question | rank_task_id | glob*>. Repeatable.")
    p.add_argument("--context-question-count", type=int, help="Maximum number of context questions per respondent.")
    p.add_argument("--include-agent-material", action="store_true", help="Include non-survey agent construction material in twin prompts.")
    p.add_argument("--agent-material-kind", action="append", help="Only include agent material of this kind. Repeatable or comma-separated.")
    p.add_argument("--agent-material-tag", action="append", help="Only include agent material with this tag. Repeatable or comma-separated.")
    p.add_argument("--max-agent-material-chars", type=int, help="Maximum agent material characters per respondent.")
    p.add_argument("--twin-material", action="append", help="Supplemental twin material file. Repeatable. Supports Markdown, JSON, or JSONL.")
    p.add_argument("--max-twin-material-chars", type=int, help="Maximum supplemental twin material characters per scenario.")
    p.add_argument(
        "--prompt-variant",
        choices=["raw", "answer-commonness-confidence"],
        default="raw",
        help="Twin prompt variant.",
    )
    p.add_argument("--model", action="append", help="EDSL model. Repeatable. Use service:model to set service per model.")
    p.add_argument("--models", help="Comma-separated EDSL models. Entries may be service:model.")
    p.add_argument("--service-name", help="EDSL service_name for unqualified models.")
    p.add_argument("--model-param", action="append", help="Model parameter. Use key=value or service:model:key=value. Repeatable.")
    p.add_argument("--job-question-name", default="response_probabilities")
    p.add_argument("--n", type=int)
    p.add_argument("--progress-bar", action="store_true")
    p.add_argument("--fresh", action="store_true")
    p.add_argument("--stop-on-exception", action="store_true")
    p.add_argument("--check-api-keys", action="store_true")
    p.add_argument("--verbose", action=argparse.BooleanOptionalAction)
    p.add_argument("--print-exceptions", action=argparse.BooleanOptionalAction)
    p.add_argument("--offload-execution", action="store_true")
    p.add_argument("--use-api-proxy", action="store_true")
    p.add_argument("--run-param", action="append", help="Additional EDSL RunParameters key=value. Repeatable.")
    p.set_defaults(func=cmd_twin_study_run)
    p = twin_study.add_parser("export-holdout", help="Export chunked EDSL jobs for true held-out question specs.")
    p.add_argument("--survey", required=True)
    p.add_argument("--output-dir", required=True, help="Directory to write chunked EDSL job files and manifest.")
    p.add_argument("--chunk-size", type=int, default=75)
    p.add_argument("--job-id-prefix", help="Prefix for chunk job ids. Defaults to <survey>_true_holdout.")
    p.add_argument("--approved-plan", help="Approved twin validation plan JSON required before exporting holdout jobs.")
    p.add_argument("--allow-unapproved", action="store_true", help="Explicitly allow an ad hoc/debug holdout export without an approved validation plan.")
    p.add_argument("--question-specs", help="JSON/JSONL file with held-out question specs.")
    p.add_argument("--question-specs-workbook", help="Workbook containing held-out question specs.")
    p.add_argument("--question-specs-sheet", default="Questions")
    p.add_argument("--question-specs-code-column", default="Question code")
    p.add_argument("--question-specs-text-column", default="Question text")
    p.add_argument("--question-specs-option-prefix", default="Answer option ")
    p.add_argument("--question-specs-labels-column", default="Answer value labels")
    p.add_argument("--heldout-question", action="append", help="Held-out question. Repeatable.")
    p.add_argument("--heldout-questions", help="Comma-separated held-out questions.")
    p.add_argument("--respondent", action="append", help="Respondent id to include. Repeatable.")
    p.add_argument("--respondents", help="Comma-separated respondent ids to include.")
    p.add_argument("--sample-respondents", type=int, help="Randomly sample this many respondents.")
    p.add_argument("--seed", type=int, help="Seed for --sample-respondents.")
    p.add_argument("--complete-cases", action="store_true", help="Only include respondents with all selected context answers.")
    p.add_argument("--balance-actual", action="store_true", help=argparse.SUPPRESS)
    p.add_argument("--stratify-actual", action="store_true", help=argparse.SUPPRESS)
    p.add_argument("--limit-respondents", type=int, help="Maximum number of respondents.")
    p.add_argument("--context-question", action="append", help="Question name to use as context. Repeatable.")
    p.add_argument("--context-questions", help="Comma-separated context question names.")
    p.add_argument("--exclude-context-question", action="append", help="Question name to exclude from context. Repeatable.")
    p.add_argument("--leakage-exclusion", action="append", help="Target-specific context exclusion as heldout_question:<context_question | rank_task_id | glob*>. Repeatable.")
    p.add_argument("--context-question-count", type=int, help="Maximum number of context questions per respondent. Omit to use all available selected context answers.")
    p.add_argument("--include-agent-material", action="store_true", help="Include non-survey agent construction material in twin prompts.")
    p.add_argument("--agent-material-kind", action="append", help="Only include agent material of this kind. Repeatable or comma-separated.")
    p.add_argument("--agent-material-tag", action="append", help="Only include agent material with this tag. Repeatable or comma-separated.")
    p.add_argument("--max-agent-material-chars", type=int, help="Maximum agent material characters per respondent.")
    p.add_argument("--twin-material", action="append", help="Supplemental twin material file. Repeatable. Supports Markdown, JSON, or JSONL.")
    p.add_argument("--max-twin-material-chars", type=int, help="Maximum supplemental twin material characters per scenario.")
    p.add_argument("--prompt-variant", choices=["raw", "answer-commonness-confidence"], default="answer-commonness-confidence")
    p.add_argument("--model", action="append", help="EDSL model. Repeatable. Use service:model to set service per model.")
    p.add_argument("--models", help="Comma-separated EDSL models. Entries may be service:model.")
    p.add_argument("--service-name", help="EDSL service_name for unqualified models.")
    p.add_argument("--model-param", action="append", help="Model parameter. Use key=value or service:model:key=value. Repeatable.")
    p.add_argument("--job-question-name", default="response_probabilities")
    p.set_defaults(func=cmd_twin_study_export_holdout)
    p = twin_study.add_parser("import-results-dir", help="Import all EDSL twin result files in a directory with stable chunk job ids.")
    p.add_argument("--survey", required=True)
    p.add_argument("--results-dir", required=True)
    p.add_argument("--job-id-prefix", help="Prefix for imported job ids. Defaults to results directory name.")
    p.add_argument("--pattern", action="append", help="Glob pattern for result files. Repeatable.")
    p.add_argument("--allow-missing-actual", action="store_true", help="Import true holdout predictions whose scenarios omit actual_answer.")
    p.add_argument("--replace", action="store_true")
    p.set_defaults(func=cmd_twin_study_import_results_dir)
    p = twin_study.add_parser("list", help="List recorded digital twin study runs.")
    p.add_argument("--survey", required=True)
    p.add_argument("--format", choices=["table", "json"], default="table")
    p.set_defaults(func=cmd_twin_study_list, table_output=True)
    p = twin_study.add_parser("show", help="Show metadata for one digital twin study run.")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", required=True)
    p.add_argument("--include-summary", action="store_true")
    p.set_defaults(func=cmd_twin_study_show)
    p = twin_study.add_parser("compare", help="Compare two or more digital twin study runs.")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", action="append", help="Job id to compare. Repeatable.")
    p.add_argument("--jobs", help="Comma-separated job ids to compare.")
    p.add_argument("--format", choices=["table", "json", "csv"], default="table")
    p.add_argument("--path", help="Write json/csv comparison output to this path.")
    p.set_defaults(func=cmd_twin_study_compare, table_output=True)
    twin_approach = subparsers.add_parser("twin-approach").add_subparsers(dest="twin_approach_command", required=True)
    p = twin_approach.add_parser("add", help="Add or update a reusable digital twin construction approach.")
    p.add_argument("--survey", required=True)
    p.add_argument("--input-path", help="JSON/YAML approach definition. If provided, inline flags are ignored.")
    p.add_argument("--approach-id")
    p.add_argument("--name")
    description_group = p.add_mutually_exclusive_group()
    description_group.add_argument("--description")
    description_group.add_argument("--description-path")
    p.add_argument("--tag", action="append")
    p.add_argument("--sample-respondents", type=int)
    p.add_argument("--seed", type=int)
    p.add_argument("--complete-cases", action="store_true")
    p.add_argument("--balance-actual", action="store_true")
    p.add_argument("--stratify-actual", action="store_true")
    p.add_argument("--limit-respondents", type=int)
    p.add_argument("--respondent", action="append")
    p.add_argument("--respondents")
    p.add_argument("--context-question", action="append")
    p.add_argument("--context-questions")
    p.add_argument("--exclude-context-question", action="append")
    p.add_argument("--leakage-exclusion", action="append")
    p.add_argument("--context-question-count", type=int)
    p.add_argument("--include-agent-material", action="store_true")
    p.add_argument("--agent-material-kind", action="append")
    p.add_argument("--agent-material-tag", action="append")
    p.add_argument("--max-agent-material-chars", type=int)
    p.add_argument("--twin-material", action="append")
    p.add_argument("--max-twin-material-chars", type=int)
    p.add_argument("--model", action="append")
    p.add_argument("--models")
    p.add_argument("--service-name")
    p.add_argument("--model-param", action="append")
    p.add_argument("--job-question-name")
    p.set_defaults(func=cmd_twin_approach_add)
    p = twin_approach.add_parser("list", help="List reusable twin construction approaches.")
    p.add_argument("--survey", required=True)
    p.add_argument("--format", choices=["table", "json"], default="table")
    p.set_defaults(func=cmd_twin_approach_list, table_output=True)
    p = twin_approach.add_parser("show", help="Show a reusable twin construction approach.")
    p.add_argument("--survey", required=True)
    p.add_argument("--approach-id", required=True)
    p.set_defaults(func=cmd_twin_approach_show)
    p = twin_approach.add_parser("note", help="Show or set markdown notes for a reusable twin approach.")
    p.add_argument("--survey", required=True)
    p.add_argument("--approach-id", required=True)
    note_group = p.add_mutually_exclusive_group()
    note_group.add_argument("--text", help="Markdown note text.")
    note_group.add_argument("--input-path", help="Path to a Markdown note file.")
    note_group.add_argument("--clear", action="store_true", help="Clear the note.")
    p.set_defaults(func=cmd_twin_approach_note)
    p = twin_approach.add_parser("scaffold", help="Write a starter JSON approach definition.")
    p.add_argument("--survey", required=True)
    p.add_argument("--approach-id", required=True)
    p.add_argument("--name")
    p.add_argument("--description")
    p.add_argument("--tag", action="append")
    p.add_argument("--context-questions")
    p.add_argument("--context-question-count", type=int, default=5)
    p.add_argument("--include-agent-material", action="store_true")
    p.add_argument("--twin-material", action="append")
    p.add_argument("--model", action="append")
    p.add_argument("--path")
    p.set_defaults(func=cmd_twin_approach_scaffold)
    p = twin_approach.add_parser("diff", help="Compare two reusable approaches or planned experiment approaches.")
    p.add_argument("--survey", required=True)
    p.add_argument("--left", required=True, help="Left approach id/name, experiment id, or job id.")
    p.add_argument("--right", required=True, help="Right approach id/name, experiment id, or job id.")
    p.add_argument("--format", choices=["table", "json", "html"], default="table")
    p.add_argument("--path", help="Write json/html output to this path.")
    p.add_argument("--show-same", action="store_true", help="Include unchanged fields in table output.")
    p.set_defaults(func=cmd_twin_approach_diff, table_output=True)

    twin_experiment = subparsers.add_parser("twin-experiment").add_subparsers(dest="twin_experiment_command", required=True)
    p = twin_experiment.add_parser("record", help="Record an approach for an existing digital twin job.")
    p.add_argument("--survey", required=True)
    p.add_argument("--job-id", required=True)
    p.add_argument("--experiment-id")
    p.add_argument("--approach", required=True, help="Short human-readable approach name.")
    description_group = p.add_mutually_exclusive_group()
    description_group.add_argument("--description", help="Markdown description of what this approach changed.")
    description_group.add_argument("--description-path", help="Path to a Markdown approach description.")
    p.add_argument("--tag", action="append", help="Experiment tag. Repeatable or comma-separated.")
    p.add_argument("--primary-metric", choices=sorted(TWIN_EXPERIMENT_METRICS), default="nll")
    p.set_defaults(func=cmd_twin_experiment_record)
    p = twin_experiment.add_parser("list", help="List recorded twin-development experiments.")
    p.add_argument("--survey", required=True)
    p.add_argument("--format", choices=["table", "json"], default="table")
    p.set_defaults(func=cmd_twin_experiment_list, table_output=True)
    p = twin_experiment.add_parser("init-plan", help="Write a starter JSON twin experiment plan.")
    p.add_argument("--survey", required=True)
    p.add_argument("--plan-id", required=True)
    p.add_argument("--path")
    p.add_argument("--heldout-question", action="append")
    p.add_argument("--heldout-questions")
    p.add_argument("--approach-id", action="append", help="Approach id to include as a plan arm. Repeatable.")
    p.add_argument("--sample-respondents", type=int)
    p.add_argument("--seed", type=int, default=123)
    p.add_argument("--stratify-actual", action="store_true", help="Stratify the respondent sample by the held-out answer.")
    p.add_argument("--context-question-count", type=int, default=5)
    p.add_argument("--context-question", action="append", help="Context question to include (repeatable).")
    p.add_argument("--context-questions", help="Comma-separated context questions to include.")
    p.add_argument("--exclude-context-question", action="append", help="Context question to exclude (repeatable).")
    p.add_argument(
        "--leakage-exclusion",
        action="append",
        help="Target-specific context exclusion as heldout:<context|rank_task_id|glob> (repeatable).",
    )
    p.add_argument("--model", action="append")
    p.add_argument(
        "--model-param",
        action="append",
        help="Per-model parameter as service:model:key=value (repeatable), e.g. "
        "google:gemini-2.5-pro:maxOutputTokens=8192. Written to the plan's defaults.model_param.",
    )
    p.add_argument("--primary-metric", choices=sorted(TWIN_EXPERIMENT_METRICS), default="nll")
    p.set_defaults(func=cmd_twin_experiment_init_plan)
    p = twin_experiment.add_parser("approve", help="Mark a reviewed twin experiment plan as approved for export/run.")
    p.add_argument("--input-path", required=True, help="JSON/YAML experiment plan.")
    p.add_argument("--survey", help="Override or validate the survey in the plan.")
    p.add_argument("--approved-by", help="Name or identifier of the approving user. Defaults to user.")
    p.add_argument("--note", help="Approval note to preserve in plan provenance.")
    p.add_argument("--estimated-cost", help="Optional estimated cost note, e.g. '$42' or 'about $40'.")
    p.add_argument("--estimated-time", help="Optional estimated runtime note.")
    p.set_defaults(func=cmd_twin_experiment_approve)
    p = twin_experiment.add_parser("export-plan", help="Export EDSL jobs from a reusable twin experiment plan.")
    p.add_argument("--input-path", required=True, help="JSON/YAML experiment plan.")
    p.add_argument("--survey", help="Override survey in the plan.")
    p.add_argument("--output-dir", help="Directory to write job files and manifest.")
    p.add_argument("--plan-id", help="Override the plan id.")
    p.add_argument("--allow-unapproved", action="store_true", help="Explicitly export a draft/unapproved plan for debugging.")
    p.set_defaults(func=cmd_twin_experiment_export_plan)
    p = twin_experiment.add_parser(
        "validate", help="Lint a plan file (resolve questions/models/counts) before approve/export."
    )
    p.add_argument("--input-path", required=True, help="JSON/YAML experiment plan.")
    p.add_argument("--survey", help="Override survey in the plan.")
    p.add_argument("--plan-id", help="Override the plan id.")
    p.set_defaults(func=cmd_twin_experiment_validate)
    p = twin_experiment.add_parser("plan-status", help="Show exported/imported status for a twin experiment plan.")
    p.add_argument("--survey", required=True)
    p.add_argument("--plan-id", required=True)
    p.add_argument("--format", choices=["table", "json"], default="table")
    p.set_defaults(func=cmd_twin_experiment_plan_status, table_output=True)
    p = twin_experiment.add_parser("note", help="Show or set markdown notes for a twin experiment plan.")
    p.add_argument("--survey", required=True)
    p.add_argument("--plan-id", required=True)
    note_group = p.add_mutually_exclusive_group()
    note_group.add_argument("--text", help="Markdown note text.")
    note_group.add_argument("--input-path", help="Path to a Markdown note file.")
    note_group.add_argument("--clear", action="store_true", help="Clear the note.")
    p.set_defaults(func=cmd_twin_experiment_note)
    p = twin_experiment.add_parser("import-plan-results", help="Import Results files that match jobs in a plan manifest.")
    p.add_argument("--manifest", required=True, help="Path to a plan export manifest.json.")
    p.add_argument("--results-dir", required=True, help="Directory containing serialized EDSL Results JSON/JSON.GZ files.")
    p.add_argument("--survey", help="Override survey from the manifest.")
    p.add_argument("--replace", action="store_true")
    p.set_defaults(func=cmd_twin_experiment_import_plan_results)
    p = twin_experiment.add_parser("package", help="Create a portable run package from an exported twin experiment plan.")
    p.add_argument("--manifest", required=True, help="Path to a plan export manifest.json.")
    p.add_argument("--output-dir", help="Directory to write package files.")
    p.add_argument("--survey", help="Override survey from the manifest.")
    p.add_argument("--plan-id", help="Override plan id from the manifest.")
    p.add_argument("--env-path", help="Explicit .env path to mention in the generated EDSL execution runbook.")
    p.set_defaults(func=cmd_twin_experiment_package)
    p = twin_experiment.add_parser("bundle", help="Create deterministic comparison, plot, and microdata artifacts for a plan.")
    p.add_argument("--survey", required=True)
    p.add_argument("--plan-id", required=True)
    p.add_argument("--metric", choices=sorted(TWIN_EXPERIMENT_METRICS), default="nll")
    p.add_argument("--model", help="Restrict bundle artifacts to one model label, e.g. openai:gpt-5.5.")
    p.add_argument("--output-dir", help="Directory to write bundle artifacts.")
    p.set_defaults(func=cmd_twin_experiment_bundle)
    p = twin_experiment.add_parser("bundle-show", help="Show paths and selected result for a bundle manifest.")
    p.add_argument("--manifest", required=True)
    p.add_argument("--format", choices=["table", "json"], default="table")
    p.set_defaults(func=cmd_twin_experiment_bundle_show, table_output=True)
    p = twin_experiment.add_parser("dashboard", help="Write a deterministic HTML dashboard for a twin experiment plan.")
    p.add_argument("--survey", required=True)
    p.add_argument("--plan-id", required=True)
    p.add_argument("--metric", choices=sorted(TWIN_EXPERIMENT_METRICS), default="nll")
    p.add_argument("--model", help="Restrict dashboard comparisons to one model label, e.g. openai:gpt-5.5.")
    p.add_argument("--bundle-manifest", help="Optional bundle manifest to link artifacts from.")
    p.add_argument("--path", help="Path to write dashboard HTML. Defaults to the plan store.")
    p.add_argument("--json-path", help="Optional path to write dashboard JSON. Defaults next to HTML.")
    p.set_defaults(func=cmd_twin_experiment_dashboard)
    p = twin_experiment.add_parser("compare", help="Rank recorded twin experiments by a selected metric.")
    p.add_argument("--survey", required=True)
    p.add_argument("--experiment-id", action="append")
    p.add_argument("--job-id", action="append")
    p.add_argument("--jobs", help="Comma-separated job ids to compare.")
    p.add_argument("--model", help="Restrict comparison to one model label, e.g. openai:gpt-5.5.")
    p.add_argument("--metric", choices=sorted(TWIN_EXPERIMENT_METRICS), default="nll")
    p.add_argument("--format", choices=["table", "json", "csv"], default="table")
    p.add_argument("--path", help="Write json/csv comparison output to this path.")
    p.set_defaults(func=cmd_twin_experiment_compare, table_output=True)
    p = twin_experiment.add_parser("plots", help="Generate deterministic plot artifacts for recorded twin experiment comparisons.")
    p.add_argument("--survey", required=True)
    p.add_argument("--experiment-id", action="append")
    p.add_argument("--job-id", action="append")
    p.add_argument("--jobs", help="Comma-separated job ids to compare.")
    p.add_argument("--model", help="Restrict plots to one model label, e.g. openai:gpt-5.5.")
    p.add_argument("--metric", choices=sorted(TWIN_EXPERIMENT_METRICS), default="nll")
    p.add_argument("--path", help="Directory to write plot manifest, SVGs, and JSON data. Defaults to the survey plot store.")
    p.add_argument("--plot-id", help="Override deterministic plot id.")
    p.set_defaults(func=cmd_twin_experiment_plots)
    p = twin_experiment.add_parser("microdata", help="Generate a standalone HTML audit table of twin microdata across experiments.")
    p.add_argument("--survey", required=True)
    p.add_argument("--experiment-id", action="append")
    p.add_argument("--job-id", action="append")
    p.add_argument("--jobs", help="Comma-separated job ids to compare.")
    p.add_argument("--model", help="Restrict audit table to one model label, e.g. openai:gpt-5.5.")
    p.add_argument("--metric", choices=sorted(TWIN_EXPERIMENT_METRICS), default="nll")
    p.add_argument("--path", help="Path to write standalone HTML. Defaults to the survey microdata store.")
    p.add_argument("--json-path", help="Optional path to write audit JSON. Defaults next to HTML.")
    p.add_argument("--microdata-id", help="Override deterministic microdata id.")
    p.add_argument("--title", help="HTML report title.")
    p.set_defaults(func=cmd_twin_experiment_microdata)
    p = twin_experiment.add_parser("select", help="Return the best recorded twin experiment for a selected metric.")
    p.add_argument("--survey", required=True)
    p.add_argument("--experiment-id", action="append")
    p.add_argument("--job-id", action="append")
    p.add_argument("--jobs", help="Comma-separated job ids to compare.")
    p.add_argument("--model", help="Restrict selection to one model label, e.g. openai:gpt-5.5.")
    p.add_argument("--metric", choices=sorted(TWIN_EXPERIMENT_METRICS), default="nll")
    p.set_defaults(func=cmd_twin_experiment_select)
    twin_benchmark = subparsers.add_parser("twin-benchmark").add_subparsers(dest="twin_benchmark_command", required=True)
    p = twin_benchmark.add_parser("run", help="Run a config-driven cross-survey twin benchmark.")
    p.add_argument("--config", required=True, help="JSON benchmark config.")
    p.add_argument("--output-dir", help="Override benchmark output directory.")
    p.add_argument("--manifest", help="Path to write benchmark run manifest.")
    p.add_argument("--dry-run", action="store_true", help="Export jobs without running model calls.")
    p.add_argument("--replace", action="store_true", help="Replace imported twin results with matching job ids.")
    p.add_argument("--env-path", help="Explicit .env file to load before running model calls (defaults to auto-discovery).")
    p.set_defaults(func=cmd_twin_benchmark_run)
    p = twin_benchmark.add_parser("report", help="Report a cross-survey twin benchmark.")
    group = p.add_mutually_exclusive_group(required=True)
    group.add_argument("--config", help="JSON benchmark config with job_id on each study.")
    group.add_argument("--manifest", help="Benchmark manifest produced by twin-benchmark run.")
    p.add_argument("--format", choices=["json", "csv", "html"], default="html")
    p.add_argument("--path", help="Write report output to this path.")
    p.set_defaults(func=cmd_twin_benchmark_report, raw_output=True)
    skills = subparsers.add_parser("skills").add_subparsers(dest="skills_command", required=True)
    p = skills.add_parser("list", help="List zwill agent skills installed with the package.")
    p.add_argument("--format", choices=["table", "json"], default="table")
    p.set_defaults(func=cmd_skills_list, table_output=True)
    p = skills.add_parser("path", help="Print the installed path for one zwill agent skill.")
    p.add_argument("name", choices=SKILL_NAMES)
    p.add_argument("--format", choices=["text", "json"], default="text")
    p.set_defaults(func=cmd_skills_path, raw_output=True)

    guide = subparsers.add_parser(
        "guide",
        help="Print the zwill agent workflow guide (or `guide list` / `guide show <name>`).",
    )
    guide_sub = guide.add_subparsers(dest="guide_command")
    p = guide_sub.add_parser("show", help="Print a bundled guide by name.")
    p.add_argument("name", nargs="?", help="Guide name; omit for the agent workflow.")
    p.set_defaults(func=cmd_guide_show, raw_output=True)
    p = guide_sub.add_parser("list", help="List the bundled guides.")
    p.add_argument("--format", choices=["table", "json"], default="table")
    p.set_defaults(func=cmd_guide_list, table_output=True)
    # Bare `zwill guide` prints the default walkthrough.
    guide.set_defaults(func=cmd_guide_show, raw_output=True, name=None, guide_command=None)

    p = subparsers.add_parser(
        "next",
        help="Show which pipeline stage you are in and the exact command to run next.",
    )
    p.add_argument("--survey", help="Survey to report the stage for (defaults to the only/first survey).")
    p.set_defaults(func=cmd_next)

    context = subparsers.add_parser("context").add_subparsers(dest="context_command", required=True)
    for command_name, func in [("add", cmd_context_add), ("set", cmd_context_set)]:
        p = context.add_parser(command_name)
        p.add_argument("--survey", required=True)
        group = p.add_mutually_exclusive_group(required=True)
        group.add_argument("--input-path")
        group.add_argument("--text")
        p.set_defaults(func=func)
    p = context.add_parser("show")
    p.add_argument("--survey", required=True)
    p.set_defaults(func=cmd_context_show)

    survey = subparsers.add_parser("survey").add_subparsers(dest="survey_command", required=True)
    p = survey.add_parser("create")
    p.add_argument("--name", required=True)
    p.set_defaults(func=cmd_survey_create)
    p = survey.add_parser("show")
    p.add_argument("--name", required=True)
    p.set_defaults(func=cmd_survey_show)
    p = survey.add_parser("report", help="Report survey questions, options, distributions, and data-quality issues.")
    p.add_argument("--survey", required=True)
    p.add_argument("--format", choices=["table", "json", "html", "csv"], default="table")
    p.add_argument("--path", help="Write json/html output, or CSV basename path for --format csv.")
    p.set_defaults(func=cmd_survey_report, table_output=True)

    raw = subparsers.add_parser("raw").add_subparsers(dest="raw_command", required=True)
    p = raw.add_parser("add")
    p.add_argument("--survey", required=True)
    p.add_argument("--id", required=True)
    p.add_argument("--input-path", required=True)
    p.add_argument("--kind", required=True)
    p.add_argument("--title", required=True)
    p.set_defaults(func=cmd_raw_add)
    p = raw.add_parser("list")
    p.add_argument("--survey", required=True)
    p.set_defaults(func=cmd_raw_list)

    question = subparsers.add_parser("question").add_subparsers(dest="question_command", required=True)
    p = question.add_parser("add")
    p.add_argument("--survey", required=True)
    p.add_argument("--question-name", required=True)
    p.add_argument("--question-type", required=True)
    p.add_argument("--question-text", required=True)
    p.add_argument("--question-option", action="append")
    p.add_argument("--option-label", action="append")
    p.add_argument("--role", default="survey_item")
    p.add_argument("--rank-task-id", help="Declare this question as an item of the named rank battery (groups items reliably instead of relying on the wording heuristic).")
    p.add_argument("--option-delimiter", help="For checkbox (multi-select) questions: the delimiter separating selected options in an answer (default '|'). Choose one that does not appear in the option labels.")
    p.add_argument("--source-raw")
    p.add_argument("--source-note")
    p.set_defaults(func=cmd_question_add)
    p = question.add_parser(
        "import",
        help="Import questions from a JSONL file (see `zwill guide show import-format`).",
        description="Import questions from a JSONL file. Each row needs at least question_name, question_type, and question_text; multiple_choice questions also need question_options. Full schema: `zwill guide show import-format`.",
    )
    p.add_argument("--survey", required=True)
    p.add_argument("--input-path", required=True, help="JSONL file, one question object per line.")
    p.set_defaults(func=cmd_question_import)

    respondent = subparsers.add_parser("respondent").add_subparsers(dest="respondent_command", required=True)
    p = respondent.add_parser("add")
    p.add_argument("--survey", required=True)
    p.add_argument("--respondent-id", required=True)
    p.add_argument("--weight", type=float, default=1.0)
    p.add_argument("--metadata", action="append")
    p.add_argument("--source-raw")
    p.add_argument("--source-note")
    p.set_defaults(func=cmd_respondent_add)
    p = respondent.add_parser(
        "import",
        help="Import respondents from a JSONL file (see `zwill guide show import-format`).",
        description="Import respondents from a JSONL file. Each row needs respondent_id; weight/metadata/source are optional. Answer import auto-creates unseen respondents. Full schema: `zwill guide show import-format`.",
    )
    p.add_argument("--survey", required=True)
    p.add_argument("--input-path", required=True, help="JSONL file, one respondent object per line.")
    p.set_defaults(func=cmd_respondent_import)

    agent_material = subparsers.add_parser("agent-material").add_subparsers(dest="agent_material_command", required=True)
    p = agent_material.add_parser("add")
    p.add_argument("--survey", required=True)
    p.add_argument("--respondent-id", required=True)
    p.add_argument("--material-id")
    p.add_argument("--kind", required=True)
    p.add_argument("--title", required=True)
    group = p.add_mutually_exclusive_group(required=True)
    group.add_argument("--input-path")
    group.add_argument("--text")
    p.add_argument("--tag", action="append", help="Tag for this material. Repeatable or comma-separated.")
    p.add_argument("--include-by-default", action="store_true")
    p.add_argument("--source-raw")
    p.add_argument("--source-note")
    p.set_defaults(func=cmd_agent_material_add)
    p = agent_material.add_parser("import")
    p.add_argument("--survey", required=True)
    p.add_argument("--input-path", required=True)
    p.set_defaults(func=cmd_agent_material_import)
    p = agent_material.add_parser("list")
    p.add_argument("--survey", required=True)
    p.add_argument("--respondent-id")
    p.add_argument("--agent-material-kind", action="append", help="Only list material of this kind. Repeatable or comma-separated.")
    p.add_argument("--agent-material-tag", action="append", help="Only list material with this tag. Repeatable or comma-separated.")
    p.set_defaults(func=cmd_agent_material_list)
    p = agent_material.add_parser("show")
    p.add_argument("--survey", required=True)
    p.add_argument("--material-id", required=True)
    p.set_defaults(func=cmd_agent_material_show)

    answer = subparsers.add_parser("answer").add_subparsers(dest="answer_command", required=True)
    p = answer.add_parser("add")
    p.add_argument("--survey", required=True)
    p.add_argument("--respondent-id", required=True)
    p.add_argument("--question", required=True)
    group = p.add_mutually_exclusive_group(required=True)
    group.add_argument("--answer")
    group.add_argument("--missing-code")
    p.set_defaults(func=cmd_answer_add)
    p = answer.add_parser(
        "import",
        help="Import answers from a JSONL file (see `zwill guide show import-format`).",
        description="Import answers from a JSONL file. Each row needs respondent_id, question, and either answer or missing_code. When the question has question_options, answer must be one of them or the row is quarantined. Full schema: `zwill guide show import-format`.",
    )
    p.add_argument("--survey", required=True)
    p.add_argument("--input-path", required=True, help="JSONL file, one answer object per line.")
    p.set_defaults(func=cmd_answer_import)

    quarantine = subparsers.add_parser("quarantine").add_subparsers(dest="quarantine_command", required=True)
    p = quarantine.add_parser("list")
    p.add_argument("--survey", required=True)
    p.set_defaults(func=cmd_quarantine_list)
    p = quarantine.add_parser("resolve")
    p.add_argument("--survey", required=True)
    p.add_argument("--issue-id", required=True)
    p.add_argument("--action", required=True)
    p.add_argument("--note", required=True)
    p.set_defaults(func=cmd_quarantine_resolve)

    return parser
